# .github/workflows/bump-version.yml

name: Bump version & Create Release

on:
  push:
    branches: [ main ]
    paths:
      - 'neurodeckit/_version.py'
      - 'setup.py'
    exclude:
      branches:
        - 'dependabot/**'
      tags:
        - '**'
      paths:
        - 'neurodeckit/_version.py'
        - 'setup.py'

permissions:
  contents: write

jobs:
  bump-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install bump2version and git config
        run: |
          python -m pip install bump2version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Bump patch version
        id: bump
        run: bump2version patch --allow-dirty
        
      - name: Get new version
        id: get_version
        run: |
          # 获取 bump2version 创建的新标签名
          NEW_TAG=$(git describe --tags --abbrev=0)
          echo "New Tag is: $NEW_TAG"
          echo "new_version=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Push new commit and tag
        run: |
          git push
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Create PyPI Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.new_version }}
          release_name: Release ${{ steps.get_version.outputs.new_version }}
          body: 'Auto release of version ${{ steps.get_version.outputs.new_version }}'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}